import Link from "next/link";

export const metadata = { title: "Terms of Service", description: "Terms governing Oramusa website services.", alternates: { canonical: "/terms" } };

export default function TermsPage() {
  return <main className="legalPage">
    <header className="legalNav shell"><Link className="brand" href="/"><span>Oram</span><em>usa</em></Link><Link href="/templates">View templates</Link></header>
    <section className="legalHero"><div className="shell"><p className="kicker">LEGAL · ORAMUSA</p><h1>Terms of Service</h1><p>Effective September 15, 2026</p></div></section>
    <article className="legalContent shell">
      <p className="legalIntro">These Terms of Service govern your use of Oramusa.com and any website design, hosting, maintenance, or related services purchased from Oramusa. A project proposal or service agreement may include additional terms. If it conflicts with these general Terms, the signed agreement controls.</p>
      <h2>1. Services</h2><p>Oramusa provides template-based website customization, hosting, maintenance, support, and related digital services. The specific pages, features, delivery schedule, and any work outside the standard plan will be confirmed in writing before work begins.</p>
      <h2>2. Subscription and payment</h2><p>The standard managed website plan is $99 per month with no website setup fee and a 12-month initial term, unless your written agreement states otherwise. Billing begins after you approve the project scope and before launch. After the initial term, the subscription continues month-to-month until canceled under the agreement. Applicable taxes and separately approved work may be charged in addition to the monthly fee.</p>
      <h2>3. Client responsibilities</h2><p>You agree to provide accurate business information, timely feedback, and materials you have the right to use, including logos, photos, trademarks, and written content. You are responsible for the accuracy, legality, and regulatory compliance of your business claims, services, offers, and content.</p>
      <h2>4. Ownership and license</h2><p>You retain ownership of your domain name and the original business materials you provide. Oramusa retains ownership of its templates, source code, design system, reusable components, tools, and underlying technology. During an active subscription, Oramusa grants you a limited, non-exclusive right to use the completed website for your business. The website design and code are not sold or transferred unless a separate written buyout agreement says so.</p>
      <h2>5. Domains and third-party services</h2><p>We recommend that you register and control your own domain. Services may rely on third parties such as domain registrars, hosting providers, email providers, analytics tools, or payment processors. Their availability and terms are outside Oramusa’s control, although we will use reasonable care when configuring services we manage.</p>
      <h2>6. Standard plan scope</h2><p>The $99 monthly plan covers one template-based website with up to five essential pages. It includes initial template customization, mobile optimization, managed hosting, SSL, routine maintenance, a standard contact or quote-request form, basic on-page SEO setup, and one batch of routine content updates per calendar month requiring up to 30 minutes of work. Routine updates are limited to existing text, customer-supplied photos, services, business hours, and contact information on existing pages. Unused update time does not roll over. Standard update requests are normally completed within three to five business days after Oramusa receives all required materials.</p>
      <h2>7. Revisions and additional work</h2><p>The initial customization includes up to two reasonable revision rounds within the approved template and project scope. Additional revisions, new pages, new layouts, custom code or applications, e-commerce, booking or payment systems, CRM or API integrations, advanced SEO campaigns, copywriting, photography, logo or branding work, major redesigns, emergency or same-day requests, and work exceeding the monthly update allowance are not included. Additional work is billed at $100 per hour with a one-hour minimum or at a fixed project price quoted by Oramusa. We will describe the work and obtain your written approval before beginning any billable additional work.</p>
      <h2>8. Requests, materials, and third-party costs</h2><p>Update requests must be submitted in writing and grouped into one monthly batch. Customer delays in providing content, approvals, credentials, or feedback do not pause subscription billing or extend the initial term. Domain registration, paid fonts, stock media, plugins, email service, advertising, and other third-party charges are the customer’s responsibility unless a written agreement expressly includes them.</p>
      <h2>9. Acceptable use</h2><p>You may not use the website or services for unlawful, deceptive, infringing, abusive, or harmful activity; to distribute malware or unsolicited messages; or to interfere with the security or operation of any service. We may suspend service when reasonably necessary to prevent harm, address nonpayment, or comply with law.</p>
      <h2>10. Cancellation and termination</h2><p>During the initial term, cancellation obligations are governed by your written service agreement. After the initial term, you may cancel month-to-month service as described in that agreement. When service ends, the Oramusa-managed website will be taken offline. Your domain and original business content remain yours, and we will reasonably assist with pointing your domain to another provider.</p>
      <h2>11. Warranties and results</h2><p>We will perform services with reasonable professional care. Except for express promises in a written agreement, services are provided “as is” and “as available.” We do not guarantee search rankings, traffic, leads, sales, uninterrupted third-party services, or specific business results.</p>
      <h2>12. Limitation of liability</h2><p>To the fullest extent permitted by law, Oramusa will not be liable for indirect, incidental, special, consequential, or lost-profit damages. Oramusa’s total liability arising from the services will not exceed the fees you paid to Oramusa during the six months immediately before the event giving rise to the claim. Some jurisdictions may not allow every limitation, so these limitations apply only as permitted by law.</p>
      <h2>13. Governing law</h2><p>These Terms are governed by the laws of the State of Florida, without regard to conflict-of-law principles. The parties will first attempt in good faith to resolve any dispute informally.</p>
      <h2>14. Changes and contact</h2><p>We may update these Terms as our services change. The effective date above identifies the latest version. Questions may be sent to <a href="mailto:hello@oramusa.com">hello@oramusa.com</a>.</p>
    </article>
    <footer className="legalFooter shell"><span>© {new Date().getFullYear()} Oramusa</span><Link href="/privacy">Privacy Policy</Link></footer>
  </main>;
}
