import Link from "next/link";

export const metadata = { title: "AUREA Real Estate Website Template", description: "A cinematic real-estate website template for agents, luxury advisors, and boutique brokerages.", alternates: { canonical: "/templates/aurea" } };
const properties=[["Lake Nona","$2,850,000","5 beds · 6 baths · 5,420 sq ft"],["Winter Park","$1,975,000","4 beds · 4.5 baths · 3,860 sq ft"],["Windermere","$3,400,000","6 beds · 7 baths · 6,110 sq ft"]];
export default function AureaTemplate(){return <main className="aurea">
<header className="aNav"><Link className="aLogo" href="#top">AUREA<span>REALTY</span></Link><nav><a href="#properties">Properties</a><a href="#approach">Approach</a><a href="#markets">Markets</a></nav><a className="aContact" href="/templates#start">Private consultation</a></header>
<section className="aHero" id="top"><img src="/aurea-realty-hero.jpg" alt="Contemporary Orlando lakefront home at blue hour"/><div className="aShade"/><div className="aHeroCopy"><p>ORLANDO · FLORIDA</p><h1>Exceptional<br/>homes deserve<br/><em>exceptional</em><br/>representation.</h1><p>Private guidance for buyers and sellers of Central Florida’s most distinctive properties.</p><div><a className="aPrimary" href="/templates#start">Begin a conversation</a><a className="aText" href="#properties">View properties ↓</a></div></div><div className="aHeroFoot"><span>ORLANDO LUXURY ADVISORY</span><span>SCROLL TO DISCOVER</span></div></section>
<section className="aStatement" id="approach"><p className="aEyebrow">THE AUREA STANDARD</p><h2>Discretion in every detail.<br/><i>Confidence</i> in every move.</h2><div><p>Real estate at this level is deeply personal. We combine precise market intelligence, thoughtful presentation, and quiet negotiation to protect what matters most to you.</p><span>$180M+ CAREER SALES<br/>12 YEARS IN CENTRAL FLORIDA<br/>TOP 1% ORLANDO ADVISORS</span></div></section>
<section className="aProperties" id="properties"><div className="aSectionHead"><p className="aEyebrow">CURATED RESIDENCES</p><h2>Featured properties.</h2></div><div className="aPropertyGrid">{properties.map(([place,price,details],i)=><article key={place}><div className={`aPropertyImage aProperty${i+1}`}><img src="/aurea-realty-hero.jpg" alt={`${place} luxury residence`}/><span>0{i+1}</span></div><p>{place} · Florida</p><h3>{price}</h3><small>{details}</small><a href="/templates#start">View residence ↗</a></article>)}</div></section>
<section className="aAdvisor"><div><p className="aEyebrow">YOUR ADVISOR</p><h2>Local insight.<br/>Global <i>perspective.</i></h2></div><div><p>From private waterfront estates to architecturally significant homes, every search and sale receives senior-level attention. One advisor. One clear strategy. No handoffs.</p><ul><li>Confidential off-market access</li><li>Data-led pricing strategy</li><li>Editorial property marketing</li><li>Skilled contract negotiation</li></ul><a href="/templates#start">Meet Alexandra →</a></div></section>
<section className="aMarkets" id="markets"><p className="aEyebrow">LOCAL EXPERTISE</p><h2>Central Florida,<br/>beautifully understood.</h2><div>{["Winter Park","Windermere","Lake Nona","Dr. Phillips"].map((m,i)=><article key={m}><span>0{i+1}</span><h3>{m}</h3><a href="/templates#start">Explore market ↗</a></article>)}</div></section>
<section className="aReview"><blockquote>“AUREA brought clarity, patience, and extraordinary judgment to every decision. Our home sold privately, beautifully, and beyond expectation.”</blockquote><p>— THE HARRIS FAMILY · WINTER PARK</p></section>
<section className="aValuation"><p className="aEyebrow">CONSIDERING A MOVE?</p><h2>Know the value<br/>of what you <i>own.</i></h2><p>Receive a confidential, property-specific market analysis—prepared personally, never automated.</p><a className="aPrimary" href="/templates#start">Request private valuation</a></section>
<footer className="aFooter"><Link className="aLogo" href="#top">AUREA<span>REALTY</span></Link><p>Distinctive homes.<br/>Discreet representation.</p><div><a href="tel:+14075550144">(407) 555-0144</a><a href="mailto:alexandra@aurearealty.com">alexandra@aurearealty.com</a></div><small>© 2026 AUREA Realty · Website template by Oramusa</small></footer>
</main>}
