"use client";
import Link from "next/link";
import { useState } from "react";

const evergreenUrl = "https://evergreen-outdoor-template.oramusa.chatgpt.site";
const templates = [
  { number:"01 / 03", type:"HOME SERVICES", name:"Evergreen", image:"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=85", alt:"Modern home surrounded by professional landscaping", copy:"A confident, premium design for businesses whose work deserves to be seen. Built around calls and quote requests.", items:["Mobile-first design","Services and project showcase","Customer reviews","Quote request form","Hosting, security, and updates"], href:evergreenUrl, external:true, visual:"", tag:"", button:"" },
  { number:"02 / 03", type:"AUTOMOTIVE", name:"Velocity", image:"/velocity-hero.jpg", alt:"Black performance coupe in a premium detailing studio", copy:"A sharp, premium design for detailers, tint shops, ceramic coating specialists, and automotive businesses.", items:["Bold mobile-first design","Services and results showcase","Customer testimonial","Quote-focused calls to action","Hosting, security, and updates"], href:"/templates/velocity", visual:"velocityPreview", tag:"blueTag", button:"velocityButton" },
  { number:"03 / 03", type:"BEAUTY & SALON", name:"ÉLAN", image:"/elan-salon-hero.jpg", alt:"Elegant guest inside a dark luxury hair salon", copy:"An editorial, dark-luxury design for salons, stylists, colorists, bridal artists, and beauty studios.", items:["Luxury mobile-first design","Service menu with pricing","Artist introductions","Customer testimonial","Booking-focused calls to action"], href:"/templates/elan", visual:"elanPreview", tag:"goldTag", button:"elanButton" },
];

export default function TemplatesPage() {
  const [status, setStatus] = useState("idle");
  const [selectedTemplate, setSelectedTemplate] = useState("");
  async function submitInterest(event) {
    event.preventDefault(); setStatus("sending");
    const form = event.currentTarget;
    const payload = Object.fromEntries(new FormData(form).entries());
    try {
      const response = await fetch("/api/leads", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(payload) });
      if (!response.ok) throw new Error("Request failed");
      form.reset(); setStatus("success");
    } catch { setStatus("error"); }
  }
  return <main className="templatesPage">
    <header className="nav shell templatesNav"><Link className="brand" href="/"><span>Oram</span><em>usa</em></Link><nav className="navLinks"><Link href="/">Home</Link><a href="#templates">Templates</a><a href="#how">How it works</a></nav><a className="navCta" href="#start">Start my website</a></header>
    <section className="templateHero"><div className="shell"><p className="kicker">ORAMUSA WEBSITE COLLECTION</p><h1>Choose your website.<br/><span>We make it yours.</span></h1><p>Professional websites for local businesses—with no large upfront bill. Pick a design, send us your details, and we handle the rest.</p><div className="pricePill"><strong>$0</strong><span>upfront</span><i/><strong>$99</strong><span>/ month</span></div></div></section>
    <section className="templateCatalog shell" id="templates"><div className="catalogHeading"><div><p className="kicker darkKicker">TEMPLATES 01–03</p><h2>Built to turn visitors<br/>into local customers.</h2></div><p>Choose a polished design for your industry. We customize the colors, content, services, photos, and contact details for your business.</p></div>
      {templates.map((template,index)=><article className={`templateCard ${index ? "templateCardSecond" : ""} ${selectedTemplate === template.name ? "templateChosen" : ""}`} key={template.name}><div className={`templateVisual ${template.visual}`}><img src={template.image} alt={template.alt}/><span className={`liveTag ${template.tag}`}>Live template</span></div><div className="templateInfo"><div><span className="templateType">{template.type}</span><span className="templateNumber">{template.number}</span></div><h3>{template.name}</h3><p>{template.copy}</p><ul>{template.items.map(item=><li key={item}>{item}</li>)}</ul><div className="templateActions">{template.external ? <a className="primary" href={template.href} target="_blank" rel="noreferrer">View live preview ↗</a> : <Link className={`primary ${template.button}`} href={template.href}>View live preview ↗</Link>}<a className="outlineDark" href="#start" onClick={()=>setSelectedTemplate(template.name)}>Choose this template</a></div></div></article>)}
    </section>
    <section className="howSection" id="how"><div className="shell"><p className="kicker">HOW IT WORKS</p><h2>From template to your website.</h2><div className="howGrid">{[["01","Choose","Pick the design that fits your business."],["02","Personalize","Send your logo, services, photos, and contact details."],["03","Approve","Review your customized website and request changes."],["04","Launch","We connect your domain and keep everything running."]].map(([n,t,p])=><div key={n}><b>{n}</b><h3>{t}</h3><p>{p}</p></div>)}</div></div></section>
    <section className="startSection shell" id="start"><div className="startCopy"><p className="kicker darkKicker">START YOUR WEBSITE</p><h2>Tell us about<br/>your business.</h2><p>No payment today. We’ll review your details and contact you to confirm the right fit before anything begins.</p><div className="included"><strong>$99/month includes</strong><span>Custom setup · Hosting · SSL security · Mobile optimization · Maintenance · Content updates</span></div></div><form className="startForm" onSubmit={submitInterest}><label className="honeypot" aria-hidden="true">Company URL<input name="website" tabIndex="-1" autoComplete="off"/></label><label className="formFull templateSelect">Selected template<select name="template" value={selectedTemplate} onChange={(event)=>setSelectedTemplate(event.target.value)} required><option value="" disabled>Choose a template</option>{templates.map(template=><option value={template.name} key={template.name}>{template.name} — {template.type}</option>)}</select></label><label>Business name<input name="business" placeholder="Your business" required/></label><label>Industry<input name="industry" placeholder="Landscaping, salon…" required/></label><label>Your name<input name="name" placeholder="First and last name" required/></label><label>Email<input name="email" type="email" placeholder="you@business.com" required/></label><label>Phone<input name="phone" type="tel" placeholder="(407) 555-0000" required/></label><label>Current website or domain<input name="domain" placeholder="Optional"/></label><label className="formFull">Anything else we should know?<textarea name="notes" placeholder="Services, goals, or questions"/></label><button className="primary formFull" type="submit" disabled={status === "sending"}>{status === "sending" ? "Sending…" : "Send my website request →"}</button>{status === "success" && <p className="formNote formFull">Thank you! Your request has been sent. We’ll contact you within one business day.</p>}{status === "error" && <p className="formNote formError formFull">We couldn’t send it right now. Please email hello@oramusa.com.</p>}</form></section>
    <footer className="footer shell"><Link className="brand footerBrand" href="/"><span>Oram</span><em>usa</em></Link><p>Beautiful websites. Zero upfront.</p><div><a href="mailto:hello@oramusa.com">hello@oramusa.com</a><span>© {new Date().getFullYear()} Oramusa</span></div></footer>
  </main>;
}
